# -*- coding: utf-8 -*-
{
    'name' : 'GescoTh lite',
    'version' : '1.2.0',
    'summary' : """
       Module de gestion complète des école secondaires officielles ou privées
    """,
    'category' : 'Gestion des écoles',
    'author' : 'Thomas ATCHA',
    'maintainer' : 'Thomas ATCHA',
    'company': 'Thomas ATCHA',
    'website' : 'https://gescoth.edu',
    'depends' : ['base','mail','website'],
    'data' : [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/eleve_view.xml',
        'wizards/liste_eleve_view.xml',
        'wizards/carte.xml',
        'views/cours_view.xml',
        'views/ecole_view.xml',
        'views/settings.xml',
        'views/examen_view.xml',
        'views/administration.xml',
        'wizards/fiche_note.xml',
        'wizards/bulletin_premiere_trimestre.xml',
        'wizards/bulletin_second_trimestre.xml',
        'wizards/bulletin_troisieme_trimestre.xml',
        'wizards/bulletin_premiere_semestre.xml',
        'wizards/bulletin_second_semestre.xml',
        'wizards/generer_note.xml',
        'views/finance_view.xml',
        'wizards/releve_paiement.xml',
        'views/template.xml',
        'data/sequence.xml',
        'data/data.xml',
        'reports/eleve_report_view.xml',
        'reports/paiement_recu.xml',
        'reports/carte_report.xml',
        'reports/liste_eleve_report.xml',
        'reports/fiche_note_report.xml',
        'reports/bulletin_premiere_trimestre_report.xml',
        'reports/bulletin_second_trimestre_report.xml',
        'reports/bulletin_troisieme_trimestre_report.xml',
        'reports/bulletin_premiere_semestre_report.xml',
        'reports/bulletin_second_semestre_report.xml',
        'reports/releve_paiement_report.xml',
        'views/website_form.xml',
        'views/cours_webiste_view.xml',
        'views/cours_chapitre_website_view.xml',
        'reports/program_report_view.xml',
        'reports/tranche_paiement_report.xml',
        'reports/prof_reports.xml',
        'data/mail_template.xml',
    ],

    'images': ['static/description/thumbnail.jpg'],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
    'license' : 'AGPL-3',
}
